import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import Skeleton from "@/components/Skeleton";
export const metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <title>IMDb Clone</title>
      </head>
      <body className="font-roboto">
        <Suspense fallback={<Skeleton />}>
          <Providers>
            <Header />
            <Navbar />
            {children}
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
